name: AltSymSquare
version: "0.1"
license: "GPL-2.0-or-later"
date: 2022-02-22
description: |
    Computing the alternating and symmetric square representations of classical groups

authors:
    - name: Lucas Wollenhaupt
      url: mailto:altsymsquare@wucas.de
    - name: Anna Sucker
      url: mailto:anna.sucker@rwth-aachen.de

maintainers:
    - name: Lucas Wollenhaupt
      url: mailto:altsymsquare@wucas.de
    - name: Anna Sucker
      url: mailto:anna.sucker@rwth-aachen.de

GAP: ">= 4.11"

www: https://wucas.github.io/AltSymSquare/
readme: README.md
packageinfo: https://wucas.github.io/AltSymSquare/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/wucas/AltSymSquare/releases/download/v0.1/AltSymSquare-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>WS22</span>]   <b class='BibAuthor'>Wollenhaupt, L. and Sucker, A.</b>,
     <i class='BibTitle'>AltSymSquare, Computing the alternating and symmetric square representations of classical groups,
             Version 0.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://wucas.github.io/AltSymSquare/">https://wucas.github.io/AltSymSquare/</a></span>.
    </p>
    

bibtex: |
    @misc{ AltSymSquare0.1,
      author =           {Wollenhaupt, L. and Sucker, A.},
      title =            {{AltSymSquare}, Computing the alternating and symmetric square representations of classical groups, {V}ersion 0.1},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href {https://wucas.github.io/AltSymSquare/} {\texttt{https://wucas.github.io/}\discretionary {}{}{}\texttt{AltSymSquare/}}},
      printedkey =       {WS22}
    }

